### ISSUE TITLE
Migrate to zsh

### ISSUE THREAD

**Issue by indexzero** [indexzero/dotfiles#17]
### zsh frameworks

* https://github.com/sorin-ionescu/prezto
* https://github.com/zimfw/zimfw

## Terminal emulator?

* https://github.com/alacritty/alacritty

## Sources

* https://project-awesome.org/unixorn/awesome-zsh-plugins
* https://www.libhunt.com/compare-zsh4humans-vs-zimfw
* https://www.libhunt.com/r/zimfw

## Recommendations

* https://starship.rs/

## Bugs

* `install.sh` fails on zsh – appears to be casing related

**Comment by blakmatrix** [comment]
FYI [The Zim wiki 'Speed' page](https://github.com/zimfw/zimfw/wiki/Speed)
